### ISSUE TITLE
Enyaq enable/disable charging does not work

### ISSUE THREAD

**Issue by dmagyar** [lendy007/homeassistant-skodaconnect#126]
When trying to toggle switch_<vin>_charging I always get an error message saying "Charging action already in progress".  I tried to stop an active charging (failed) and also starting a new charge - no luck :(

```
2022-07-01 14:14:38 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140130499686848] Charging action already in progress
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/skodaconnect/switch.py", line 57, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.9/site-packages/skodaconnect/dashboard.py", line 558, in turn_on
    await self.vehicle.set_charger('start')
  File "/usr/local/lib/python3.9/site-packages/skodaconnect/vehicle.py", line 396, in set_charger
    raise SkodaRequestInProgressException('Charging action already in progress')
skodaconnect.exceptions.SkodaRequestInProgressException: Charging action already in progress
```

**Comment by Farfar** [comment]
Have you tried restart of Home Assistant? Might be that it got hung up on a finished action.

**Comment by dmagyar** [comment]
Thanks, it works most of the time - other times there might be issues with the Skoda servers :( 
One more question: how can I set the charging current? On the Enyaq the value is "Reduced A" which is not numeric.
I'd like to create a virtual switch that can toggle between reduced and full but it does not work as the plugin uses non-numeric values...

**Comment by Farfar** [comment]
> One more question: how can I set the charging current? On the Enyaq the value is "Reduced A" which is not numeric.

Use a service call (yaml mode and not gui mode) and send "Reduced" or "Maximum" as current:
```yaml
service: skodaconnect.set_charger_max_current
data:
  device_id: xxxxxxxxxxxxxxxxxxxx
  current: Reduced
```
