### ISSUE TITLE
number entity template for changing charger limitation (call service)

### ISSUE THREAD

**Issue by ChristophCaina** [lendy007/homeassistant-skodaconnect#140]
**Describe the bug**
I am trying to create a template number slider to set the charging limitation directly from the Dashboard.

Now, I am getting the following errors when I try to change the charge limitation:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skodaconnect/__init__.py:357
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:31:39 (1 occurrences)
Last logged: 14:31:39

[140323683915168] Failed to execute set charger - 'int' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 446, in set_charger
    response = await self._connection.setCharging(self.vin, data)
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/connection.py", line 1622, in setCharging
    return await self._setSkodaAPI('charging', vin, json = data)
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/connection.py", line 1604, in _setSkodaAPI
    request_id = response.get('id', 0)
AttributeError: 'int' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 109, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/usr/src/homeassistant/homeassistant/components/template/number.py", line 162, in async_set_native_value
    await self.async_run_script(
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 407, in async_run_script
    return await script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/skodaconnect/__init__.py", line 357, in set_charge_limit
    if await car.set_charge_limit(limit) is True:
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 503, in set_charge_limit
    return await self.set_charger(data)
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 473, in set_charger
    raise SkodaException(f'Failed to execute set charger - {error}')
skodaconnect.exceptions.SkodaException: Failed to execute set charger - 'int' object has no attribute 'get'
```
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/skodaconnect/__init__.py:357
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:31:39 (1 occurrences)
Last logged: 14:31:39

[140323683915168] Failed to execute set charger - 'int' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 446, in set_charger
    response = await self._connection.setCharging(self.vin, data)
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/connection.py", line 1622, in setCharging
    return await self._setSkodaAPI('charging', vin, json = data)
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/connection.py", line 1604, in _setSkodaAPI
    request_id = response.get('id', 0)
AttributeError: 'int' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 109, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/usr/src/homeassistant/homeassistant/components/template/number.py", line 162, in async_set_native_value
    await self.async_run_script(
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 407, in async_run_script
    return await script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/skodaconnect/__init__.py", line 357, in set_charge_limit
    if await car.set_charge_limit(limit) is True:
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 503, in set_charge_limit
    return await self.set_charger(data)
  File "/usr/local/lib/python3.10/site-packages/skodaconnect/vehicle.py", line 473, in set_charger
    raise SkodaException(f'Failed to execute set charger - {error}')
skodaconnect.exceptions.SkodaException: Failed to execute set charger - 'int' object has no attribute 'get'
```
```
Logger: skodaconnect.vehicle
Source: custom_components/skodaconnect/__init__.py:357
Integration: Skoda Connect (documentation, issues)
First occurred: 14:31:39 (1 occurrences)
Last logged: 14:31:39

Failed to {'limit': 80, 'action': 'chargelimit'} charging - 'int' object has no attribute 'get'
```

here's my template:

```
template:
  - number:
    - name: mycar_charge_limitation
      unique_id: 'mycar_charge_limitation'
      state: "{{ states('sensor.mycar_minimum_charge_level') }}"
      set_value:
      - service: skodaconnect.set_charge_limit
        data:
          limit: "{{ value | int(0) }}"
          device_id: 2c1c0d706fe211bd09c09d56a282aecc
      step: '10'
      min: '10'
      max: '100'
```

**Comment by Farfar** [comment]
Is 80 a valid value for your car? For most it's only 0-50

**Comment by ChristophCaina** [comment]
In the App and also the Service I can Set the value Up to 100 since it isn't a hybrid Car.

But I think it is working now - Not Sure what the issue was...

**Comment by Farfar** [comment]
> In the App and also the Service I can Set the value Up to 100 since it isn't a hybrid Car.
> 
> But I think it is working now - Not Sure what the issue was...

Glad it's working for you!
