### ISSUE TITLE
KeyError vehicle

### ISSUE THREAD

**Issue by bslefevre** [lendy007/homeassistant-skodaconnect#146]
**Describe the bug**
After updating to the latest HASS and Skoda Connect I'm getting this error

**Latest working release**
Worked on HASS 2022.6 and a few versions back of Skoda Connect (don't know exactly which one)

**Debug logs**

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/skodaconnect/__init__.py:740 
Integration: Skoda Connect (documentation, issues) 
First occurred: 6:17:47 PM (1 occurrences) 
Last logged: 6:17:47 PM

Error setting up entry bslefevre@gmail.com for skodaconnect
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/skodaconnect/__init__.py", line 139, in async_setup_entry
    coordinator = SkodaCoordinator(hass, entry, update_interval)
  File "/home/homeassistant/.homeassistant/custom_components/skodaconnect/__init__.py", line 740, in __init__
    self.vin = entry.data[CONF_VEHICLE].upper()
KeyError: 'vehicle'

**Comment by bslefevre** [comment]
Fixed it by removing my Skoda Kodiaq 2019 and reinstalling the module!
