### ISSUE TITLE
Services in need of spin doesn't work

### ISSUE THREAD

**Issue by Sha-Darim** [lendy007/homeassistant-skodaconnect#20]
**Describe the bug**
I cannot make any calls that requires the SPIN, like turn on the heater or lock doors. I know the SPIN is corect, checked it with original app. But the error message suggests it is wrong!?

**Latest working release**
New user

**Debug logs**
```
2021-02-27 14:45:07 INFO (MainThread) [homeassistant.components.automation.carheater_start] Initialized trigger Carheater start,
2021-02-27 14:46:26 ERROR (MainThread) [skodaconnect.connection] Could not generate security token (maybe wrong SPIN?), error: non-hexadecimal number found in fromhex() arg at position 3,
2021-02-27 14:46:26 WARNING (MainThread) [skodaconnect.vehicle] Failed to lock vehicle - non-hexadecimal number found in fromhex() arg at position 3,
2021-02-27 14:46:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1798031200] Lock action failed,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service,
    await hass.services.async_call(,
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call,
    task.result(),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service,
    await handler.job.target(service_call),
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service,
    await self.hass.helpers.service.entity_service_call(,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call,
    future.result()  # pop exception if have,
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call,
    await coro,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call,
    await result,
  File "/config/custom_components/skodaconnect/lock.py", line 36, in async_lock,
    await self.instrument.lock(),
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 321, in lock,
    return await self.vehicle.set_lock('lock', self.spin),
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 475, in set_lock,
    raise Exception('Lock action failed'),
Exception: Lock action failed,
```

**Installation:**
 - Home Assistant variant: Hass 2021.3.0 on Docker
 - Python version 3.8

**Additional context**
My config:
```
skodaconnect: !include skodaconnect.yaml

#skodaconnect.yaml
username: !secret skoda_user
password: !secret skoda_pass
spin: !secret skoda_spin
scandinavian_miles: false
scan_interval:
  minutes: 1
name:
  tmblsfefs833388: 'Kodiaq'

```

**Comment by Farfar** [comment]
The log indicates there's something wrong with the SPIN, please make sure that there's no extra characters in your config (secrets.yaml)

**Comment by Sha-Darim** [comment]
Well this was a bummer. Everything is probably in order - it was I who forgot to activate the "lock" feature properly 👎

**Comment by Farfar** [comment]
> Well this was a bummer. Everything is probably in order - it was I who forgot to activate the "lock" feature properly

Thank you for reporting back!
