### ISSUE TITLE
Adding and updating sensors combustion_range and combined_range fails

### ISSUE THREAD

**Issue by mhosse** [lendy007/homeassistant-skodaconnect#22]
**Describe the bug**
HA logs errors about the two sensors combustion_range and combined_range at start and at every update

**Latest working release**
--

**Debug logs**
```
Logger: homeassistant.components.sensor
Source: custom_components/skodaconnect/sensor.py:27
Integration: Sensor (documentation, issues)
First occurred: 10:37:43 (3 occurrences)
Last logged: 10:37:43

Error adding entities for domain sensor with platform skodaconnect
Error while setting up skodaconnect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/skodaconnect/sensor.py", line 27, in state
    return self.instrument.state
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 114, in state
    val = super().state
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 59, in state
    return self.vehicle.get_attr(self.attr)
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 528, in get_attr
    return find_path(self.attrs, attr)
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/utilities.py", line 86, in find_path
    return find_path(src[path[0]], path[1:])
KeyError: 'combustion_range'
```
```
Logger: homeassistant.util.logging
Source: util/logging.py:99
First occurred: 10:38:44 (2 occurrences)
Last logged: 10:38:44

Exception in async_write_ha_state when dispatching 'skodaconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state sstate = self.state File "/config/custom_components/skodaconnect/sensor.py", line 27, in state return self.instrument.state File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 114, in state val = super().state File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 59, in state return self.vehicle.get_attr(self.attr) File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 528, in get_attr return find_path(self.attrs, attr) File "/usr/local/lib/python3.8/site-packages/skodaconnect/utilities.py", line 86, in find_path return find_path(src[path[0]], path[1:]) KeyError: 'combustion_range'
Exception in async_write_ha_state when dispatching 'skodaconnect.updated': () Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state sstate = self.state File "/config/custom_components/skodaconnect/sensor.py", line 27, in state return self.instrument.state File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 114, in state val = super().state File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 59, in state return self.vehicle.get_attr(self.attr) File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 528, in get_attr return find_path(self.attrs, attr) File "/usr/local/lib/python3.8/site-packages/skodaconnect/utilities.py", line 86, in find_path return find_path(src[path[0]], path[1:]) KeyError: 'combined_range'

```
**Installation:**
 - Home Assistant variant: Supervised
 - Python version: 3.8
 - Python library versions: [pip_list.txt](https://github.com/lendy007/homeassistant-skodaconnect/files/6089616/pip_list.txt)
 - skodaconnect version: 1.0.36

**Comment by Farfar** [comment]
Should be fixed in v.1.0.37
