### ISSUE TITLE
No module named 'skodaconnect'

### ISSUE THREAD

**Issue by renejorissen** [lendy007/homeassistant-skodaconnect#34]
I try to use the skodaconnect integration and I am relatively new to the custom components. I copied the files under custom_components to the local HASS VM - folder: /config/custom_components/skodaconnect.

I also added the config to configurations.yaml. Now I receive the following error message when rebooting HASS.

```
Logger: homeassistant.loader
Source: custom_components/skodaconnect/__init__.py:25
Integration: skodaconnect
First occurred: 11:19:00 AM (5 occurrences)
Last logged: 11:33:04 AM
Error loading custom_components.skodaconnect. Make sure all dependencies are installed

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 609, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/skodaconnect/__init__.py", line 25, in <module>
    from skodaconnect import Connection
ModuleNotFoundError: No module named 'skodaconnect'
```

**Comment by Farfar** [comment]
You are missing the skodaconnect Python library. Either install it manually with 'pip install skodaconnect' or equivalent command to suit your environment.

An easier approach is using HACS, see [here](https://hacs.xyz/docs/installation/prerequisites)
