### ISSUE TITLE
Issue after installing v1.0.42-RC1

### ISSUE THREAD

**Issue by bslefevre** [lendy007/homeassistant-skodaconnect#42]
**Describe the bug**
After updating to the lateste RC1

**Latest working release**
v1.0.40-RC5

**Debug logs**
` 2021-06-30 16:08:15 ERROR (MainThread) [homeassistant.setup] Setup failed for skodaconnect: unknown error
 Traceback (most recent call last):
   File "/srv/homeassistant/venv_3.8.9/lib/python3.8/site-packages/homeassistant/setup.py", line 200, in _async_setup_component
     component = integration.get_component()
   File "/srv/homeassistant/venv_3.8.9/lib/python3.8/site-packages/homeassistant/loader.py", line 490, in get_component
     cache[self.domain] = importlib.import_module(self.pkg_path)
   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 779, in exec_module
   File "<frozen importlib._bootstrap_external>", line 916, in get_code
   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/home/homeassistant/.homeassistant/custom_components/skodaconnect/__init__.py", line 254
     return True
     ^
 IndentationError: unexpected indent
`

**Installation:**
 - Home Assistant variant: core-2021.6.3
 - Python version 3.8
 - Python library versions ["python3 -m pip list"]

**Additional context**
Not appliccable

**Comment by bslefevre** [comment]
After removing and reinstalling the component in HACS it seems to be working again
Will test it in a few hours, hopefully the `charging_cable_connected` will work!

**Comment by Farfar** [comment]
Well I released RC2 that fixed a typo ;)
