### ISSUE TITLE
citigo eiv climatization not working v1.0.42-RC2

### ISSUE THREAD

**Issue by stefanuc111** [lendy007/homeassistant-skodaconnect#46]
**Describe the bug**

I've a skoda citigo eiv and I've this switch in home assistant: switch.e_citigo_sty_61_e1f_electric_climatisation

 The switch desn't work anymore when pressed it says 'Vehicle' object has no attribute 'set_climater'

**Latest working release**

**Debug logs**

`2021-06-30 23:37:21 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2976384696] 'Vehicle' object has no attribute 'set_climater'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/config/custom_components/skodaconnect/switch.py", line 51, in async_turn_on
await self.instrument.turn_on()
File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 411, in turn_on
await self.vehicle.set_climatisation('electric')
File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 538, in set_climatisation
return await self.set_climater(data, spin)
AttributeError: 'Vehicle' object has no attribute 'set_climater'`

**Installation:**
 - Home Assistant variant:  Hass OS

**Comment by Farfar** [comment]
Fixed in library version 1.0.43
