### ISSUE TITLE
citigo eiv departure switches not workings on  v1.0.42-RC2

### ISSUE THREAD

**Issue by stefanuc111** [lendy007/homeassistant-skodaconnect#47]
**Describe the bug**

trying to switch on/off departure times produces "name 'data' is not defined"

**Debug logs**
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/skodaconnect/switch.py", line 51, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/dashboard.py", line 604, in turn_on
    await self.vehicle.set_timer_active(id=1, action="on")
  File "/usr/local/lib/python3.8/site-packages/skodaconnect/vehicle.py", line 375, in set_timer_active
    data['id'] = id
NameError: name 'data' is not defined`

**Installation:**
 - Home Assistant variant: Hass OS
 - Python version 3.8

**Comment by Farfar** [comment]
Thanks, I noticed myself that I mucked something up. The latest commit for the library should already have it fixed but I will wait until I can test it before I publish new release.

**Comment by Farfar** [comment]
Tested and working in upcoming release 1.0.43-RC3
