### ISSUE TITLE
Can't login with 1.0.48

### ISSUE THREAD

**Issue by szafran81** [lendy007/homeassistant-skodaconnect#58]
**Describe the bug**
Can't login after updating to 1.0.48

**Latest working release**
I think it was 1.0.45

**Debug logs**
```
2021-08-27 17:49:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-27 17:49:06 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'automation', 'map', 'ssdp', 'blueprint', 'nodered', 'mqtt', 'counter', 'group', 'broadlink', 'input_number', 'persistent_notification', 'onewire', 'cast', 'timer', 'sun', 'input_datetime', 'system_health', 'network', 'tag', 'configurator', 'samsungtv', 'history', 'media_source', 'plex', 'met', 'input_boolean', 'webostv', 'energy', 'logbook', 'my', 'hacs', 'tts', 'scene', 'trace', 'input_select', 'default_config', 'updater', 'zone', 'smartthinq_sensors', 'dhcp', 'input_text', 'skodaconnect', 'script', 'zeroconf', 'mobile_app', 'tuya'}
2021-08-27 17:49:07 INFO (MainThread) [homeassistant.setup] Setting up skodaconnect
2021-08-27 17:49:07 INFO (MainThread) [homeassistant.setup] Setup of domain skodaconnect took 0.0 seconds
2021-08-27 17:52:03 DEBUG (MainThread) [custom_components.skodaconnect.config_flow] Creating connection to Skoda Connect
2021-08-27 17:52:03 INFO (MainThread) [skodaconnect.connection] Init Skoda Connect library, version 1.0.48
2021-08-27 17:52:03 DEBUG (MainThread) [skodaconnect.connection] Using service https://msg.volkswagen.de
2021-08-27 17:52:03 DEBUG (MainThread) [skodaconnect.connection] Initiating new login
2021-08-27 17:52:03 INFO (MainThread) [skodaconnect.connection] Connecting to Skoda native API
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Got authorization endpoint
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Found item: ('_csrf', '')
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Found item: ('relayState', '')
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Found item: ('email', '')
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Found item: ('hmac', '')
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Authenticating with email and password.
2021-08-27 17:52:04 DEBUG (MainThread) [skodaconnect.connection] Parsing login response.
2021-08-27 17:52:05 DEBUG (MainThread) [skodaconnect.connection] Login successful, received authorization code.
2021-08-27 17:52:05 DEBUG (MainThread) [skodaconnect.connection] Trying to fetch user identity tokens.
2021-08-27 17:52:05 DEBUG (MainThread) [skodaconnect.connection] Attempting to verify token for client skoda. Token: , pubkey: <cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at>, audience: ['', '', 'https://api.vas.eu.dp15.vwg-connect.com', 'https://api.vas.eu.wcardp.io']
2021-08-27 17:52:05 DEBUG (MainThread) [skodaconnect.connection] Token for skoda verified OK.
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Got authorization endpoint
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Found item: ('_csrf', '')
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Found item: ('relayState', '')
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Found item: ('email', '')
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Found item: ('hmac', '')
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Authenticating with email and password.
2021-08-27 17:52:06 DEBUG (MainThread) [skodaconnect.connection] Parsing login response.
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Login successful, received authorization code.
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Trying to fetch user identity tokens.
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Attempting to verify token for client connect. Token: , pubkey: <cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at>, audience: ['', '', 'https://api.vas.eu.dp15.vwg-connect.com', 'https://api.vas.eu.wcardp.io']
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Token for connect verified OK.
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v2/garage/vehicles"
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/garage/vehicles" returned with status code [200]
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Skoda native API returned no cars
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Going to call vehicle updates
2021-08-27 17:52:07 DEBUG (MainThread) [skodaconnect.connection] Calling update function for all vehicles
```

**Installation:**
 - Home Assistant variant: Core
 - Python version 3.8.10
 - Python library versions:
```
attrs                  19.3.0
Automat                0.8.0
blinker                1.4
certifi                2019.11.28
chardet                3.0.4
Click                  7.0
cloud-init             21.2
colorama               0.4.3
command-not-found      0.3
configobj              5.0.6
constantly             15.1.0
cryptography           2.8
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
dnspython              1.16.0
entrypoints            0.3
gpg                    1.13.1-unknown
httplib2               0.14.0
hyperlink              19.0.0
idna                   2.8
importlib-metadata     1.5.0
incremental            16.10.1
Jinja2                 2.10.1
jsonpatch              1.22
jsonpointer            2.0
jsonschema             3.2.0
keyring                18.0.1
language-selector      0.1
launchpadlib           1.10.13
lazr.restfulclient     0.14.2
lazr.uri               1.0.3
Markdown               3.1.1
MarkupSafe             1.1.0
more-itertools         4.2.0
mysqlclient            2.0.3
netifaces              0.10.4
oauthlib               3.1.0
packaging              20.3
pexpect                4.6.0
pip                    20.0.2
pyasn1                 0.4.2
pyasn1-modules         0.2.1
pycrypto               2.6.1
pycryptodome           3.10.1
Pygments               2.3.1
PyGObject              3.36.0
PyHamcrest             1.9.0
PyJWT                  1.7.1
pyOpenSSL              19.0.0
pyparsing              2.4.6
pyrsistent             0.15.5
pyserial               3.4
python-apt             2.0.0+ubuntu0.20.4.5
python-debian          0.1.36ubuntu1
PyYAML                 5.3.1
requests               2.22.0
requests-unixsocket    0.2.0
SecretStorage          2.3.1
service-identity       18.1.0
setuptools             45.2.0
simplejson             3.16.0
six                    1.14.0
sos                    4.1
ssh-import-id          5.10
systemd-python         234
tinytuya               1.2.7
tuyapower              0.0.25
Twisted                18.9.0
ubuntu-advantage-tools 27.2
ufw                    0.36
urllib3                1.25.8
wadllib                1.3.3
wheel                  0.34.2
zipp                   1.0.0
zope.interface         4.7.1
```

**Additional context**
Previous version configured via yaml worked fine. This one shows that I don't have any cars in the garage (and I do).
Weird.

**Comment by Farfar** [comment]
Should be solved in 1.0.50

**Comment by szafran81** [comment]
Thank you for the fast response.
I've updated to .50 using HACS, and now I'm getting:
![image](https://user-images.githubusercontent.com/2608332/131215014-e0592b4e-076e-4449-a09f-dc8d91807237.png)
It basically says:
Unable to load configuration interface.
This happens just after selecting to add Skoda Connect from the HA Integrations

**Comment by Farfar** [comment]
> Thank you for the fast response.
> I've updated to .50 using HACS, and now I'm getting:
> ![image](https://user-images.githubusercontent.com/2608332/131215093-afd95972-2585-4617-b371-1d4b2b4fa6b5.png)
> It basically says:
> Unable to load configuration interface.
> This happens just after selecting to add Skoda Connect from the HA Integrations
> 
> EDIT: I've tried removing and reinstalling the integration, but that didn't help.
> 
> EDIT2: Something from the logs:
> 
> ```
> 2021-08-28 12:39:29 ERROR (MainThread) [aiohttp.server] Error handling request
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
>     resp = await self._request_handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
>     resp = await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
>     return await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
>     return await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
>     return await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
>     return await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
>     return await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
>     return await handler(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 135, in handle
>     result = await result
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 128, in post
>     return await super().post(request)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
>     result = await method(view, request, *args, **kwargs)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 72, in post
>     result = await self._flow_mgr.async_init(
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 153, in async_init
>     flow, result = await task
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 171, in _async_init
>     flow = await self.async_create_flow(handler, context=context, data=data)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
>     integration.get_platform("config_flow")
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 498, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 503, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 844, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 981, in get_code
>   File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/szafran/.homeassistant/custom_components/skodaconnect/__init__.py", line 280
>     "enabled": service_call.data.get("enabled"),
>     ^
> SyntaxError: invalid syntax
> ```
> 
> EDIT3: Tried again 'HACS -> Integrations -> Skoda Connect -> Uninstall -> Reboot PC -> HACS -> Integrations -> Add repo -> Skoda Connect -> Install -> Reboot PC -> HA Options -> Integrations -> Add integration -> Skoda Connect' and the same thing as above.

I re-released as v1.0.51. There was a missing "," on the line above. I did not have that issue though on my install.

**Comment by szafran81** [comment]
The car was added this time (from what I can see everything looks just like on .4x).
I also didn't see any errors in the logs, so now everything looks to be ok.
Thank you.

**Comment by Farfar** [comment]
> The car was added this time (from what I can see everything looks just like on .4x).
> I also didn't see any errors in the logs, so now everything looks to be ok.
> Thank you.

Excellent. Closing issue.
