### ISSUE TITLE
Window Heating does not work on Enyaq

### ISSUE THREAD

**Issue by sc0ps** [lendy007/homeassistant-skodaconnect#88]
Window Heating does not work on my skoda enyaq .
when switching on via HA I get the following message
(Failed to call service switch/turn_on. Remote control of climatisation funktions is not supported.)

v.1.0.61

**Comment by sc0ps** [comment]
even if I switch on the window heating in the my skoda app.  does not change the window heating status in home assistant

**Comment by Farfar** [comment]
Will look into this as soon as I have the time

**Comment by Farfar** [comment]
> even if I switch on the window heating in the my skoda app. does not change the window heating status in home assistant

Is there an option in the app to start only window heating? How do you enable/disable window heating in the app?

**Comment by sc0ps** [comment]
![Screenshot_20211118-002627_MyKODA.jpg](https://user-images.githubusercontent.com/83918766/142298646-3370b0f7-4d72-4822-80d1-ab92c31f7b9f.jpg) 

yes for sure there is.  in the air conditioning tab, you can switch it on see image.  sorry text in my skoda app are in dutch

**Comment by Farfar** [comment]
> ![Screenshot_20211118-002627_MyKODA.jpg](https://user-images.githubusercontent.com/83918766/142298646-3370b0f7-4d72-4822-80d1-ab92c31f7b9f.jpg)
> 
> yes for sure there is. in the air conditioning tab, you can switch it on see image. sorry text in my skoda app are in dutch

No worries. If you enable it without starting the climatisation, does it stay on if you exit the app and open it up again?

**Comment by sc0ps** [comment]
> climatisation

if I switch on the window heating in the my skoda app and then close the my skoda app and open it again, the window heating in the app is indeed still on

**Comment by Farfar** [comment]
> > No worries. If you enable it without starting the climatisation, does it stay on if you exit the app and open it up again?
> 
> if I switch on the window heating in the my skoda app and then close the my skoda app and open it again, the window heating in the app is indeed still on

Ok. But this switch doesn't enable window heating immediately, it only enables it when you start next climatisation correct?

**Comment by sc0ps** [comment]
>Ok. But this switch doesn't enable window heating immediately, it only enables it when you start next climatisation correct?

that is correct when I switch on the window heating option in the my skoda app.  then the window heating function switches to automatic in the car.  

when I turn on the window heating switch in Home assistant.  then the window heating does not switch to automatic in the car.  even if I then start the climatization

![20211118_144029.jpg](https://user-images.githubusercontent.com/83918766/142428788-ee883742-4529-4125-9b27-a0e77e156118.jpg)

**Comment by akadna** [comment]
Any update on this? I also got the error.

The error "**Failed to call service switch/turn_off. Air conditioning action failed**" trigger immediately in UI (1< sec), and I got this in HA log (debug)

`2022-02-19 16:47:01 WARNING (MainThread) [skodaconnect.vehicle] Failed to execute air conditioning request - 'type'
2022-02-19 16:47:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140663559994384] Air conditioning action failed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/skodaconnect/switch.py", line 57, in async_turn_on
    await self.instrument.turn_on()
  File "/usr/local/lib/python3.9/site-packages/skodaconnect/dashboard.py", line 586, in turn_on
    await self.vehicle.set_window_heating('start')
  File "/usr/local/lib/python3.9/site-packages/skodaconnect/vehicle.py", line 738, in set_window_heating
    return await self._set_aircon(data)
  File "/usr/local/lib/python3.9/site-packages/skodaconnect/vehicle.py", line 925, in _set_aircon
    raise SkodaException('Air conditioning action failed')
skodaconnect.exceptions.SkodaException: Air conditioning action failed`

The switch/state is not reflecting the state in the skoda app. If I toogle the state in app , the new 'windowHeatingEnabled' is correctly fetch from api with True/False values (according to app settings), but HA UI not updated.

**Comment by Farfar** [comment]
There's no update on this yet, sorry. I only have limited time for this at the moment and this is not top priority.

**Comment by Farfar** [comment]
I have an attempted fix for this in the works. Will update when new version is released.

**Comment by Farfar** [comment]
I need new debug data with recent library version >=1.0.26 to see if I've made any progress in fixing this problem

**Comment by RamonQu** [comment]
I hope this information helps you forward. Especially the status polling mechanism...

Set Window Heater toggle in homeassistant-skodaconnect (1.0.72) gives the following information in DEBUG:

```
2022-12-12 17:19:15.606 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/status"
2022-12-12 17:19:15.612 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/settings"
2022-12-12 17:19:15.826 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/settings" returned with status code [200], response: {'targetTemperatureInKelvin': 291.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}
2022-12-12 17:19:15.867 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/status" returned with status code [200], response: {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'Off'}, {'windowLocation': 'Rear', 'state': 'Off'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}
2022-12-12 17:19:15.868 INFO (MainThread) [skodaconnect.connection] Returning with data {'airConditioning': {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'Off'}, {'windowLocation': 'Rear', 'state': 'Off'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}, 'airConditioningSettings': {'targetTemperatureInKelvin': 291.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}}
2022-12-12 17:19:15.869 DEBUG (MainThread) [skodaconnect.vehicle] Attempting to update aircon settings with data {'airConditioningSettings': {'targetTemperatureInKelvin': 291.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}, 'type': 'UpdateSettings'}.
2022-12-12 17:19:15.869 DEBUG (MainThread) [skodaconnect.vehicle] Sending request
2022-12-12 17:19:15.870 DEBUG (MainThread) [skodaconnect.connection] HTTP POST "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin={VIN}"
2022-12-12 17:19:16.096 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin={VIN}" returned with status code [201], response: {'id': '6397548426cae44305831b94', 'status': 'InProgress', 'deeplink': ''}
2022-12-12 17:19:16.096 DEBUG (MainThread) [skodaconnect.connection] Data call returned: {'id': '6397548426cae44305831b94', 'status': 'InProgress', 'deeplink': ''}
2022-12-12 17:19:16.097 DEBUG (MainThread) [skodaconnect.connection] Request returned with state "InProgress", request id: 6397548426cae44305831b94
2022-12-12 17:19:16.098 WARNING (MainThread) [skodaconnect.connection] Failure during get request status: '{VIN}'
2022-12-12 17:19:16.104 WARNING (MainThread) [skodaconnect.vehicle] Exception encountered while waiting for request status: Failure during get request status: '{VIN}'
```


From the MySkoda-App perspective this works like this:


Skoda app sends POST request to

https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests/start-window-heating

```
{
  "vin" : “{VIN}“
}

```

Returns:

```
{
	"id": “{transactionID}”,
	"status": "InProgress",
	"deeplink": ""
}
```


The MySkoda App keeps polling every 5 seconds to get an statusupdate, it looks like the homeassistantskodaconnect is giving up quite fast. Sometimes it takes longer than a minute and 12 calls to be successful


GET update status on https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests/{transactionID}

```
{
	"id": "{transactionID}",
	"status": "InProgress",
	"deeplink": ""
}
```


After four times (in this case, but most like much slower) the same message as above I got finaly the Succesful-message

```
{
	"id": "{transactionID}",
	"status": "Successful",
	"deeplink": ""
}

```

The current status (Front- and Rear-window-heating is on) also reflects in GET call to:

https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/status

```
{
	"remainingTimeToReachTargetTemperatureInSeconds": 0,
	"state": "Off",
	"trigger": "OFF",
	"windowsHeatingStatuses": [{
		"windowLocation": "Front",
		"state": "On"
	}, {
		"windowLocation": "Rear",
		"state": "On"
	}],

	"seatHeatingSupport": {
		"frontLeftAvailable": true,
		"frontRightAvailable": true,
		"rearLeftAvailable": false,
		"rearRightAvailable": false
	}

}
```

Turning the window heater off works the same but the call goes to https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests/stop-window-heating

**Comment by RamonQu** [comment]
![aircoEnyaqv2](https://user-images.githubusercontent.com/113984457/207106373-7c6fcb6c-528a-48d2-864c-136effb370d7.jpg)

I've got two buttons in the MySkoda app (I own an Enyaq with software ME3.0)

Button A starts the Window Heater directly. Button B accepts the window heater to be used (probably with heating the car).

I did a traceback on both. 

**Button A:**

Set Window Heater toggle in homeassistant-skodaconnect (1.0.72) gives the following information in DEBUG:

```
2022-12-12 17:19:15.606 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/status"
2022-12-12 17:19:15.612 DEBUG (MainThread) [skodaconnect.connection] HTTP GET "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/settings"
2022-12-12 17:19:15.826 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/settings" returned with status code [200], response: {'targetTemperatureInKelvin': 291.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}
2022-12-12 17:19:15.867 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/status" returned with status code [200], response: {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'Off'}, {'windowLocation': 'Rear', 'state': 'Off'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}
2022-12-12 17:19:15.868 INFO (MainThread) [skodaconnect.connection] Returning with data {'airConditioning': {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'Off'}, {'windowLocation': 'Rear', 'state': 'Off'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}, 'airConditioningSettings': {'targetTemperatureInKelvin': 291.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}}
2022-12-12 17:19:15.869 DEBUG (MainThread) [skodaconnect.vehicle] Attempting to update aircon settings with data {'airConditioningSettings': {'targetTemperatureInKelvin': 291.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': True, 'frontRightEnabled': False}}, 'type': 'UpdateSettings'}.
2022-12-12 17:19:15.869 DEBUG (MainThread) [skodaconnect.vehicle] Sending request
2022-12-12 17:19:15.870 DEBUG (MainThread) [skodaconnect.connection] HTTP POST "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin={VIN}"
2022-12-12 17:19:16.096 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin={VIN}" returned with status code [201], response: {'id': '{transactionID}', 'status': 'InProgress', 'deeplink': ''}
2022-12-12 17:19:16.096 DEBUG (MainThread) [skodaconnect.connection] Data call returned: {'id': '{transactionID}', 'status': 'InProgress', 'deeplink': ''}
2022-12-12 17:19:16.097 DEBUG (MainThread) [skodaconnect.connection] Request returned with state "InProgress", request id: {transactionID}
2022-12-12 17:19:16.098 WARNING (MainThread) [skodaconnect.connection] Failure during get request status: '{VIN}'
2022-12-12 17:19:16.104 WARNING (MainThread) [skodaconnect.vehicle] Exception encountered while waiting for request status: Failure during get request status: '{VIN}'
```


From the MySkoda-App perspective this works like this:


Skoda app sends POST request to

https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests/start-window-heating

```
{
  "vin" : “{VIN}“
}

```

Returns:

```
{
	"id": “{transactionID}”,
	"status": "InProgress",
	"deeplink": ""
}
```


The MySkoda App keeps polling every 5 seconds to get an statusupdate, it looks like the homeassistantskodaconnect is giving up quite fast. Sometimes it takes longer than a minute and 12 calls to be successful


GET update status on https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests/{transactionID}

```
{
	"id": "{transactionID}",
	"status": "InProgress",
	"deeplink": ""
}
```


After four times (in this case, but most of the time it's much slower) the same message as above is returned, but finally I get the Succesful-message

```
{
	"id": "{transactionID}",
	"status": "Successful",
	"deeplink": ""
}

```

The current status (Front- and Rear-window-heating is on) also reflects in a GET call to:

https://api.connect.skoda-auto.cz/api/v1/air-conditioning/{VIN}/status

```
{
	"remainingTimeToReachTargetTemperatureInSeconds": 0,
	"state": "Off",
	"trigger": "OFF",
	"windowsHeatingStatuses": [{
		"windowLocation": "Front",
		"state": "On"
	}, {
		"windowLocation": "Rear",
		"state": "On"
	}],

	"seatHeatingSupport": {
		"frontLeftAvailable": true,
		"frontRightAvailable": true,
		"rearLeftAvailable": false,
		"rearRightAvailable": false
	}

}
```

Turning the window heater off works the same but the call goes to https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests/stop-window-heating


**Button B:**

Turn it on

POST https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin={VIN}

```
{
"type": "UpdateSettings",
"airConditioningSettings": {
"targetTemperatureInKelvin": 291.14999389648438,
"windowHeatingEnabled": true,
"airConditioningAtUnlock": false,
"zonesSettings": {
"frontLeftEnabled": true,
"frontRightEnabled": false
}
},
"deeplink": "skodaconnect:\/\/addon\/RemoteAirConditioningAddon?vin={VIN}"
}

```


Turning it off

POST [https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin={VIN}](https://api.connect.skoda-auto.cz/api/v1/air-conditioning/operation-requests?vin=%7BVIN%7D)

```
{
"type": "UpdateSettings",
"airConditioningSettings": {
"targetTemperatureInKelvin": 291.14999389648438,
"windowHeatingEnabled": false,
"airConditioningAtUnlock": false,
"zonesSettings": {
"frontLeftEnabled": true,
"frontRightEnabled": false
}
},
"deeplink": "skodaconnect:\/\/addon\/RemoteAirConditioningAddon?vin={VIN}"
}
```

After that is start polling the same as with Button A

**Comment by Farfar** [comment]
Thank you for the info @RamonQu!
I've implemented window heater in code. Please try out 1.1.2 (beta) and report back any issues. I'll fix them as I am notified since I can't test Enyaq specifics myself.

**Comment by Farfar** [comment]
Tested working with borrowed account on 1.1.4.
