### ISSUE TITLE
Integration stopped working yesterday

### ISSUE THREAD

**Issue by szafran81** [lendy007/homeassistant-skodaconnect#97]
**Describe the bug**
Yesterday (18.12.2021) I've noticed that the integration stopped working.

**Latest working release**
v1.0.62

**Debug logs**
This is what my basic logs show:
```
2021-12-19 15:13:48 WARNING (MainThread) [skodaconnect.connection] Failed to aquire information about vehicle with VIN TMBER...
2021-12-19 15:13:48 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Fetch vehicles failed with error: No vehicles were found for given account!
2021-12-19 15:13:48 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 267, in async_configure
    raise ValueError(
ValueError: Show progress can only transition to show progress or show progress done.
```

Please tell me if debug logs are needed, or even something more? And if this even is a bug or just some API errors (eg. Skodas fault).

**Installation:**
 - HAOS VM (on Ubuntu Server 20.04 host)

**Comment by XalaTheShepard** [comment]
It does not seem a bug in the integration, but a bug in the API of Skoda Connect itself. In the browser Skoda Connect shows my garage / cars perfectly, but the Skoda Connect smartphone app can not find any car. Also adding the cars again does not work. Since this issue in the smartphone app, I experience the same issue in HA.

**Comment by Farfar** [comment]
This kind of issue are related to the service itself and not the integration. VW Group does maintenance or something during weekends since I've noticed most issues start then.
Usually it resolves itself in a couple of days.

**Comment by szafran81** [comment]
Ups... forgot to check the mobile app before posting... just checked if it works via the web.
Sorry for that - my mobile app also has an empty garage.
